### PR TITLE
fix: Execution logic for default topic validators in WakuRelay

### PR DESCRIPTION
**Pull request by hishboy**
# Description
This PR addresses an issue in the WakuRelay's topic validation mechanism. Previously, if topicValidators were not set for a specific topic but defaultTopicValidators were provided, the logic incorrectly bypassed executing these default validators. This was due to the check being performed before merging the defaultTopicValidators. The proposed change ensures we correctly assess the combined list of validators after merging both topicValidators and defaultTopicValidators. This means that all validators will always be considered, regardless of whether specific topic validators are set.

### CODE REVIEW

**Comment by richard-ramos** [comment]
Good catch!

**Review by richard-ramos — APPROVED** [review]

**Review by chaitanyaprem — APPROVED** [review]
Nice!
LGTM

Curious to know if you using go-waku to build something.

**Comment by hishboy** [comment]
> Nice! LGTM
> 
> Curious to know if you using go-waku to build something.

Hey @chaitanyaprem, yep we're building tribes decentralized network using go-waku and js-waku (https://www.tribes.xyz)

**Comment by chaitanyaprem** [comment]
> > Nice! LGTM
> > Curious to know if you using go-waku to build something.
> 
> Hey @chaitanyaprem, yep we're building tribes decentralized network using go-waku and js-waku (https://www.tribes.xyz)

Did not know that, Awesome! 
Would love to know more on how you are using Waku.
Is it just for chat or any other off-chain communication as well?

Specifically how are you guys using go-waku and js-waku? 

Do reach out to us on [discord](https://discord.waku.org/) in case you require any support or discussion.

**Comment by hishboy** [comment]
@chaitanyaprem yep I'm in the discord. Username `hishboy`. I'll ping you there and discuss our plans. Thanks!

**Comment by hishboy** [comment]
Hey @richard-ramos / @chaitanyaprem, it seems like the checks are stuck for a while (see screenshot). Is it common to take that long to complete?

image

**Comment by chaitanyaprem** [comment]
> Hey @richard-ramos / @chaitanyaprem, it seems like the checks are stuck for a while (see screenshot). Is it common to take that long to complete?
> image

Nah, they are generally done in max of 10 mins. 
@jakubgs , can you take a look? Looks like CI checks are stuck from more than an hour or so.

**Pull request merged**
