### PR TITLE
chore: error handling in params construction

### PR DESCRIPTION
**Pull request by kaichaosun**
# Description

The change add error handling based on this comment https://github.com/waku-org/go-waku/pull/930#discussion_r1407134171
~This seems a bit tedius to me and brings less value. How do you think?~

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]
I like the change. It will for sure improve the dev experience, since then a developer will know for sure that they cannot use both options at the same time (before they could but then the nameservers would have been ignored, so this will potentially save them debugging time and for us, having to give support in case such scenario happens)

**Review by chaitanyaprem — APPROVED** [review]
LGTM

**Comment by kaichaosun** [comment]
codeclimate check is failed with excessive return statement, should I change it somewhere in their site or add the config in go-waku repo?
I have no clue why test-ci failed.

**Comment by chaitanyaprem** [comment]
> codeclimate check is failed with excessive return statement, I loose the check for 6 return statements. I can also refactor the code to reduce the return statement, but have 4 return statement looks pretty strict.
> 
> Any clue why test-ci failed? It's happy now. 😂

Codeclimate check is not mandatory as it has some weird checks like this return statements which are not possible to enforce all the time. 

test-ci failure could be due to a flaky test, have noticed this sometimes before as well. 

But, I don't think increasing return statements to 6 helps much, i would suggest if we can make codeclimate ignore this in total. @richard-ramos WDYT?

**Comment by richard-ramos** [comment]
> Any clue why test-ci failed? It's happy now.

Probably due to the flaky postgresql tests

**Comment by chaitanyaprem** [comment]
> > But, I don't think increasing return statements to 6 helps much, i would suggest if we can make codeclimate ignore this in total. @richard-ramos WDYT?
> 
> We have 3 options here:
> 
>     1. Disable it
> 
>     2. Mark as wont fix in code climate
> 
> 
> I kinda like option 2 because having multiple returns could be a sign of code smell, or a function that needs to be split up.

Let's go with option-2. Even i like it better. 

@kaichaosun , please revert the codeclimate check change and then you are good to merge this PR.

**Pull request merged**
