### PR TITLE
chore: filter v2 tests coverage improvement

### PR DESCRIPTION
**Pull request by romanzac**
Description
Batch of tests for Waku Filter v2 to improve coverage

Changes
Tests available to run:
cd go-waku/waku/v2/protocol/filter
go test

### CODE REVIEW

**Comment by romanzac** [comment]
@chaitanyaprem I would like to wrap up filter tests with covering certain error cases. I wonder if you see the same value in https://github.com/waku-org/go-waku/pull/931/commits/49435a833f0cc937d8c86992dde11ff060c6c223 I'd say integrator might appreciate to receive error when sending UnsubscribeAll with wrong peer.ID (host.ID) by mistake. Being an attacker would  probably give up looking at peer ID length. So I would say benefit >> security risk to provide error?

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem I would like to wrap up filter tests with covering certain error cases. I wonder if you see the same value in [49435a8](https://github.com/waku-org/go-waku/commit/49435a833f0cc937d8c86992dde11ff060c6c223) I'd say integrator might appreciate to receive error when sending UnsubscribeAll with wrong peer.ID (host.ID) by mistake. Being an attacker would probably give up looking at peer ID length. So I would say benefit >> security risk to provide error?

Good one, looks like as of now the result will just be an empty instead of an error indicating no subscription found for the peer which is not a great dev ex.
This could be addressed so that the API returns appropriate error, but I don't understand how it is some secuirty risk.

**Comment by romanzac** [comment]
> > @chaitanyaprem I would like to wrap up filter tests with covering certain error cases. I wonder if you see the same value in [49435a8](https://github.com/waku-org/go-waku/commit/49435a833f0cc937d8c86992dde11ff060c6c223) I'd say integrator might appreciate to receive error when sending UnsubscribeAll with wrong peer.ID (host.ID) by mistake. Being an attacker would probably give up looking at peer ID length. So I would say benefit >> security risk to provide error?
> 
> Good one, looks like as of now the result will just be an empty instead of an error indicating no subscription found for the peer which is not a great dev ex. This could be addressed so that the API returns appropriate error, but I don't understand how it is some secuirty risk.

It is not a security risk, or it is just a negligible one. To compare, there is also no error when we unsubscribe from non existent topic. Here, topic could be very short string, and could be potentially guessed by executing enough unsubscribe calls. Attacker could then listen to conversation or spam (up to rate the limit). It is good we don't return any error code at that case.

I've created improvement https://github.com/waku-org/go-waku/issues/933

**Comment by chaitanyaprem** [comment]
> > > @chaitanyaprem I would like to wrap up filter tests with covering certain error cases. I wonder if you see the same value in [49435a8](https://github.com/waku-org/go-waku/commit/49435a833f0cc937d8c86992dde11ff060c6c223) I'd say integrator might appreciate to receive error when sending UnsubscribeAll with wrong peer.ID (host.ID) by mistake. Being an attacker would probably give up looking at peer ID length. So I would say benefit >> security risk to provide error?
> > 
> > 
> > Good one, looks like as of now the result will just be an empty instead of an error indicating no subscription found for the peer which is not a great dev ex. This could be addressed so that the API returns appropriate error, but I don't understand how it is some secuirty risk.
> 
> It is not a security risk, or it is just a negligible one. To compare, there is also no error when we unsubscribe from non existent topic. Here, topic could be very short string, and could be potentially guessed by executing enough unsubscribe calls. Attacker could then listen to conversation or spam (up to rate the limit). It is good we don't return any error code at that case.
> 
> I've created improvement #933

We need to return the proper errors so that dev ex is better. 
Wrt an attacker listening to conversation, they can listen to any messages as long as they are subscribed to a pubsubTopic using relay (since this is a gossipsub network), which is why it is recommended for applications to encrypt their data so that 3rd parties cannot read the actual content. 
Also note that there is no rate limit when it comes to listening/receiving messages, the only rate-limit is for publishing messages to the network (in order to avoid spam).

**Review by chaitanyaprem — APPROVED** [review]
LGTM

**Review by richard-ramos — APPROVED** [review]

**Comment by romanzac** [comment]
> > > > @chaitanyaprem I would like to wrap up filter tests with covering certain error cases. I wonder if you see the same value in [49435a8](https://github.com/waku-org/go-waku/commit/49435a833f0cc937d8c86992dde11ff060c6c223) I'd say integrator might appreciate to receive error when sending UnsubscribeAll with wrong peer.ID (host.ID) by mistake. Being an attacker would probably give up looking at peer ID length. So I would say benefit >> security risk to provide error?
> > > 
> > > 
> > > Good one, looks like as of now the result will just be an empty instead of an error indicating no subscription found for the peer which is not a great dev ex. This could be addressed so that the API returns appropriate error, but I don't understand how it is some secuirty risk.
> > 
> > 
> > It is not a security risk, or it is just a negligible one. To compare, there is also no error when we unsubscribe from non existent topic. Here, topic could be very short string, and could be potentially guessed by executing enough unsubscribe calls. Attacker could then listen to conversation or spam (up to rate the limit). It is good we don't return any error code at that case.
> > I've created improvement #933
> 
> We need to return the proper errors so that dev ex is better. Wrt an attacker listening to conversation, they can listen to any messages as long as they are subscribed to a pubsubTopic using relay (since this is a gossipsub network), which is why it is recommended for applications to encrypt their data so that 3rd parties cannot read the actual content. Also note that there is no rate limit when it comes to listening/receiving messages, the only rate-limit is for publishing messages to the network (in order to avoid spam).

@chaitanyaprem  Would you like to fix https://github.com/waku-org/go-waku/issues/933 some time soon ? This PR has a test which depends on fixing #933, so it won't pass required checks before fixing.

**Comment by chaitanyaprem** [comment]
> > > > > @chaitanyaprem I would like to wrap up filter tests with covering certain error cases. I wonder if you see the same value in [49435a8](https://github.com/waku-org/go-waku/commit/49435a833f0cc937d8c86992dde11ff060c6c223) I'd say integrator might appreciate to receive error when sending UnsubscribeAll with wrong peer.ID (host.ID) by mistake. Being an attacker would probably give up looking at peer ID length. So I would say benefit >> security risk to provide error?
> > > > 
> > > > 
> > > > Good one, looks like as of now the result will just be an empty instead of an error indicating no subscription found for the peer which is not a great dev ex. This could be addressed so that the API returns appropriate error, but I don't understand how it is some secuirty risk.
> > > 
> > > 
> > > It is not a security risk, or it is just a negligible one. To compare, there is also no error when we unsubscribe from non existent topic. Here, topic could be very short string, and could be potentially guessed by executing enough unsubscribe calls. Attacker could then listen to conversation or spam (up to rate the limit). It is good we don't return any error code at that case.
> > > I've created improvement #933
> > 
> > 
> > We need to return the proper errors so that dev ex is better. Wrt an attacker listening to conversation, they can listen to any messages as long as they are subscribed to a pubsubTopic using relay (since this is a gossipsub network), which is why it is recommended for applications to encrypt their data so that 3rd parties cannot read the actual content. Also note that there is no rate limit when it comes to listening/receiving messages, the only rate-limit is for publishing messages to the network (in order to avoid spam).
> 
> @chaitanyaprem Would you like to fix #933 some time soon ? This PR has a test which depends on fixing #933, so it won't pass required checks before fixing.

Just merged the fix on to master. If you update your branch, you should have the fix in it and ci would pass :)

**Pull request merged**
