### PR TITLE
fix: panic due to enr having more than 300 bytes

### LINKED ISSUE #1138: bug: panic observed in go-discover
**Describe the bug**
While running code from this PR, observed a crash with below backtrace.

@richard-ramos , i thought this was handled with some recover method within go-discover. But looks like this condition of enr greater than 300 bytes got hit and created a crash. Now, this doesn't look like local node's record rather some external node record

```
2024/06/26 10:15:20 websocket: failed to close network connection: close tcp 192.168.1.5:61832->8.218.74.73:443: use of closed network connection
panic: enode: can't sign record: record bigger than 300 bytes

goroutine 2234124 [running]:
github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).sign(0x2400110e000)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:310 +0x41c
github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).Node(0x2400110e000)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:122 +0x158
github.com/waku-org/go-discover/discover.(*UDPv5).Self(...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:178
github.com/waku-org/go-discover/discover.(*UDPv5).lookupWorker(0x24003a69d00, 0x2400a81f050, {0x49, 0xc9, 0xc, 0x7b, 0x44, 0x98, 0x4c, 0x96, ...})
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:313 +0x154
github.com/waku-org/go-discover/discover.(*UDPv5).lookupSelf.(*UDPv5).newLookup.func1(0x45fe71fd67876148?)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:296 +0x38
github.com/waku-org/go-discover/discover.(*lookup).query(0x2400e4d5ef0, 0x2400a81f050, 0x240061d4380?)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:144 +0x98
created by github.com/waku-org/go-discover/discover.(*lookup).startQueries in goroutine 546
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/lookup.go:126 +0x1d4
SIGABRT: Abnormal termination.
make: *** [run-macos] Abort trap: 6
```

Attaching logs 
[logs.tgz](https://github.com/user-attachments/files/15982527/logs.tgz)

### PR DESCRIPTION
**Pull request by richard-ramos**
Fixes #1138 
Requires status-im/go-ethereum@v1.10.25-status.15

### CODE REVIEW

**Review by chaitanyaprem — APPROVED** [review]
Interesting, did not realize that localNode limit can be triggered within discover..but kind of makes sense. 
Hope this fix works, because we can't reproduce it as often

Approving as i understood the approach.

**Comment by chaitanyaprem** [comment]
Looks like fix did not work, crashed again

```
panic: enode: can't sign record: record bigger than 300 bytes

goroutine 3085 [running]:
github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).sign(0x14000b32b00)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:310 +0x41c
github.com/ethereum/go-ethereum/p2p/enode.(*LocalNode).Node(0x14000b32b00)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/ethereum/go-ethereum/p2p/enode/localnode.go:122 +0x158
github.com/waku-org/go-discover/discover/v5wire.(*Codec).makeHandshakeAuth(0x14002518960, {0xb5, 0x6f, 0x57, 0x2b, 0xf8, 0x39, 0xd3, 0xc9, 0x6c, ...}, ...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5wire/encoding.go:376 +0x1dc
github.com/waku-org/go-discover/discover/v5wire.(*Codec).encodeHandshakeHeader(0x14002518960, {0xb5, 0x6f, 0x57, 0x2b, 0xf8, 0x39, 0xd3, 0xc9, 0x6c, ...}, ...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5wire/encoding.go:318 +0x64
github.com/waku-org/go-discover/discover/v5wire.(*Codec).Encode(0x14002518960, {0xb5, 0x6f, 0x57, 0x2b, 0xf8, 0x39, 0xd3, 0xc9, 0x6c, ...}, ...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5wire/encoding.go:181 +0x1a0
github.com/waku-org/go-discover/discover.(*UDPv5).send(0x14004cd4500, {0xb5, 0x6f, 0x57, 0x2b, 0xf8, 0x39, 0xd3, 0xc9, 0x6c, ...}, ...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:607 +0x90
github.com/waku-org/go-discover/discover.(*UDPv5).sendCall(0x14004cd4500, 0x14008639a00)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:591 +0x13c
github.com/waku-org/go-discover/discover.(*UDPv5).handleWhoareyou(0x14004cd4500, 0x14006e47360, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:753 +0x338
github.com/waku-org/go-discover/discover.(*UDPv5).handle(0x14002518960?, {0x10b70b190?, 0x14006e47360?}, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...}, ...)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:706 +0x84
github.com/waku-org/go-discover/discover.(*UDPv5).handlePacket(0x14004cd4500, {0x14004bc4000, 0x3f, 0x500}, 0x14004cd4500?)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:665 +0x288
github.com/waku-org/go-discover/discover.(*UDPv5).dispatch(0x14004cd4500)
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:523 +0x3a4
created by github.com/waku-org/go-discover/discover.ListenV5 in goroutine 527
	/Users/prem/Code/status-desktop/vendor/status-go/vendor/github.com/waku-org/go-discover/discover/v5_udp.go:134 +0x12c
SIGABRT: Abnormal termination.
make: *** [run-macos] Abort trap: 6
```

**Comment by chaitanyaprem** [comment]
Looks like crash is happening more frequently with this fix.
https://github.com/status-im/status-mobile/pull/20553#issuecomment-2194510085

**Comment by richard-ramos** [comment]
image

Damn, i wouldnt have expected this PR to even make things worse!

**Comment by richard-ramos** [comment]
@chaitanyaprem I updated the code to do +- what the localnode does when signing a ENR in https://github.com/ethereum/go-ethereum/blob/master/p2p/enode/localnode.go#L287-L295  (the code that causes the panic). 

Theoretically this shouldnt cause a failure now, because we're signing the message and instead of relying on Node() panicing, wecan see if there is going to be an error or not,  also, just in case, i delete any of the fields that might be set by the localnode, just to make sure we are not storing extra information.

I was not able to reproduce the issue tho. Do you consistently get the error? can you help me taking this go-waku version for a test drive?

**Comment by chaitanyaprem** [comment]
> @chaitanyaprem I updated the code to do +- what the localnode does when signing a ENR in https://github.com/ethereum/go-ethereum/blob/master/p2p/enode/localnode.go#L287-L295 (the code that causes the panic).
> 
> Theoretically this shouldnt cause a failure now, because we're signing the message and instead of relying on Node() panicing, wecan see if there is going to be an error or not, also, just in case, i delete any of the fields that might be set by the localnode, just to make sure we are not storing extra information.
> 
> I was not able to reproduce the issue tho. Do you consistently get the error? can you help me taking this go-waku version for a test drive?

Tested new build over the weekend and did not notice the crash. Was also running build without this fix and noticed that crashed in between, so now i am guessing the fix is ready. 
We can merge this now.

**Comment by richard-ramos** [comment]
Nice!

**Pull request merged**
