### PR TITLE
chore: update rebased gossipsub from libp2p

### PR DESCRIPTION
**Pull request by chaitanyaprem**
ref PR https://github.com/waku-org/go-libp2p-pubsub/pull/2

### CODE REVIEW

**Review by richard-ramos — APPROVED** [review]

**Comment by richard-ramos** [comment]
Let's see now!

**Comment by chaitanyaprem** [comment]
> Let's see now!

Tried that locally already and didn't work. This seems to be something else. 
Can't we configure nix to not use vendors model and just build with go.mod?

**Comment by richard-ramos** [comment]
cc: @jakubgs

**Comment by richard-ramos** [comment]
I'll try creating a tag in the meantime. Because nix used to work with replaces (it does with go-ethereum) so maybe there's something weird going on when using a commit.

**Comment by jakubgs** [comment]
>Can't we configure nix to not use vendors model and just build with go.mod?

@chaitanyaprem @richard-ramos but it does use `go.mod`, you just need to update the SHA:
https://github.com/waku-org/go-waku/blob/bc16c74f2ec9642ff961bf30ebeeca4f3dbf5e87/default.nix#L28-L29
Just like the comment says.

**Comment by chaitanyaprem** [comment]
> > Can't we configure nix to not use vendors model and just build with go.mod?
> 
> @chaitanyaprem @richard-ramos but it does use `go.mod`, you just need to update the SHA:
> 
> https://github.com/waku-org/go-waku/blob/bc16c74f2ec9642ff961bf30ebeeca4f3dbf5e87/default.nix#L28-L29
> 
> Just like the comment says.

we did try updating the SHA, but still it was giving an error https://github.com/waku-org/go-waku/pull/1185#issuecomment-2285782335

**Comment by jakubgs** [comment]
Okay, there is a bug here, because there's two `buildPackage` functions:
https://github.com/waku-org/go-waku/blob/d3b51130599d55e1388e08c5a6cdc5c62a894b8c/flake.nix#L16-L35
You changed the one in `flake.nix` but the on in `default.nix` is in effect. Here's the fix:

- [`go-waku#c324e3df`](https://github.com/status-im/go-waku/commit/c324e3df) - fix: remove duplicate buildPackage function from flake.nix

Rebase and fix the hash.

**Comment by chaitanyaprem** [comment]
> Okay, there is a bug here, because there's two `buildPackage` functions:
> 
> https://github.com/waku-org/go-waku/blob/d3b51130599d55e1388e08c5a6cdc5c62a894b8c/flake.nix#L16-L35
> 
> You changed the one in `flake.nix` but the on in `default.nix` is in effect. Here's the fix:
> 
>     * [`go-waku#c324e3df`](https://github.com/status-im/go-waku/commit/c324e3df) - fix: remove duplicate buildPackage function from flake.nix
> 
> 
> Rebase and fix the hash.

ok, Thanks!

i used to get the updated hash by running nix build locally using below command. But running that command throws error. is there any other way to get the hash to update it in `default.nix` file?

```
prem@Prems-MacBook-Pro go-waku % nix build --extra-experimental-features nix-command --extra-experimental-features flakes

warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
error: builder for '/nix/store/p4gpdqcc2q785l1f2s5rs1415mrwk7hm-go-waku.drv' failed with exit code 1;
       last 10 log lines:
       > Building subPackage ./cmd/waku
       > go: inconsistent vendoring in /private/tmp/nix-build-go-waku.drv-0/source:
       > 	github.com/libp2p/go-libp2p-pubsub@v0.12.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
       > 	github.com/libp2p/go-libp2p-pubsub@v0.12.0: is replaced in go.mod, but not marked as replaced in vendor/modules.txt
       > 	github.com/libp2p/go-libp2p-pubsub@v0.11.0: is marked as explicit in vendor/modules.txt, but not explicitly required in go.mod
       > 	github.com/libp2p/go-libp2p-pubsub@v0.11.0: is marked as replaced in vendor/modules.txt, but not replaced in go.mod
       >
       > 	To ignore the vendor directory, use -mod=readonly or -mod=mod.
       > 	To sync the vendor directory, run:
       > 		go mod vendor
       For full logs, run 'nix-store -l /nix/store/p4gpdqcc2q785l1f2s5rs1415mrwk7hm-go-waku.drv'.

```

**Comment by jakubgs** [comment]
You can try modifying the hash to be clearly invalid, that will force Nix to re-evaluate that part.

**Comment by chaitanyaprem** [comment]
Closing this as #1208 already has these changes included and some more.

**Pull request closed without merging**
