### PR TITLE
chore: add rate limiter option to lightpush

### PR DESCRIPTION
**Pull request by richard-ramos**
# Description
Adds an optional rate limit (that we should set in status-go).
Fixes https://github.com/waku-org/go-waku/issues/667

### CODE REVIEW

**Review by chaitanyaprem — APPROVED** [review]
LGTM

**Comment by chaitanyaprem** [comment]
I am wondering if we should also provide an option to specify rate-limit config like WithRateLimit(<req/sec>) itself for cross language scenarios where limiter cannot be passed from application

**Comment by richard-ramos** [comment]
> cross language scenarios
you mean, interop with other languages via bindings? if that's the case, it's a nice idea and worth adding to nwaku c-bindings.

**Comment by chaitanyaprem** [comment]
> > cross language scenarios
> 
> you mean, interop with other languages via bindings? if that's the case, it's a nice idea and worth adding to nwaku c-bindings.

Yup, but i am thinking it would be better to add it to the golang API as well so that it would be uniform across all language bindings. WDYT?

**Comment by richard-ramos** [comment]
Not sure! I'm wary of adding new code to go-waku that is not going to be used, since we're replacing it by nwaku

**Pull request merged**
