### PR TITLE
chore: bumped libp2p and pubsub to 0.32.2 and 0.10 respectively

### PR DESCRIPTION
**Pull request by chaitanyaprem**
# Description
Noticed there is already another PR #851  to bump libp2p to 0.32.0.

Not sure which one to take forward though. Looks like we can take this forward as this also needs updating https://github.com/waku-org/go-libp2p-rendezvous

WDYT @richard-ramos

### CODE REVIEW

**Comment by richard-ramos** [comment]
I created the following PR just to test if we'd run into issues:
https://github.com/status-im/status-go/pull/4522  (it includes this [commit ](https://github.com/waku-org/go-waku/pull/857/commits/3a32060c8c543b173b43ef581c36236b37cda811) from https://github.com/waku-org/go-waku/pull/857 to downgrade to go 1.19), but it still fails because go-libp2p now requires go 1.20
```
[2024-01-03T21:58:36.191Z] vendor/github.com/quic-go/quic-go/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
[2024-01-03T21:58:36.191Z] note: module requires Go 1.20
```

So, looks like we gotta update status-go to use Go 1.20 just like it was done with 1.19 here: https://github.com/status-im/status-go/pull/3371  I'll try that

**Comment by richard-ramos** [comment]
Now with go 1.20, there's a more concerning error in the build for android:
```
[2024-01-03T22:11:27.888Z] unable to import bind/java: [-: # golang.org/x/mobile/bind/java

[2024-01-03T22:11:27.888Z] /nix/store/njgsm9h0wscli413vg98f76yx09crg8z-gomobile-unstable-2022-05-18/src/golang.org/x/mobile/bind/java/context_android.go:9:10: fatal error: jni.h: No such file or directory

[2024-01-03T22:11:27.888Z]     9 | //#include <jni.h>

[2024-01-03T22:11:27.888Z]       |          ^~~~~~~

[2024-01-03T22:11:27.888Z] compilation terminated.]

[2024-01-03T22:11:27.888Z] /nix/store/njgsm9h0wscli413vg98f76yx09crg8z-gomobile-unstable-2022-05-18/bin/gomobile: /nix/store/njgsm9h0wscli413vg98f76yx09crg8z-gomobile-unstable-2022-05-18/bin/gobind -lang=go,java -outdir=/home/jenkins/workspace/status-go_prs_android_PR-4522@tmp/gomobile-work -tags=gowaku_no_rln github.com/status-im/status-go/mobile failed: exit status 1
```

Let's try go 1.21

**Comment by richard-ramos** [comment]
I couldnt update to go1.21. Will continue troubleshooting in PR https://github.com/status-im/status-go/pull/4522

**Comment by richard-ramos** [comment]
Btw, if we want to use this PR, we also must take into account the discussion in https://github.com/waku-org/go-waku/pull/851#discussion_r1379687848 about dropping support to mplex in js-waku and nwaku.

**Comment by chaitanyaprem** [comment]
> Btw, if we want to use this PR, we also must take into account the discussion in [#851 (comment)](https://github.com/waku-org/go-waku/pull/851#discussion_r1379687848) about dropping support to mplex in js-waku and nwaku.

Not necessary, because we can still use mplex by specifying it as an option. And the package still exists and can be imported from a different path. But, my suggestion there was to eventually move away from mplex and only use yamux which can be done once all clients remove mplex support.

**Comment by richard-ramos** [comment]
Just rebased and updated the PR to include go-libp2p-rendezvous. I was able to get status-go to work with 1.20 in https://github.com/status-im/status-go/pull/4522, so we can merge this PR!

**Review by richard-ramos — APPROVED** [review]

**Pull request merged**
