### PR TITLE
Update readme to test PR assign worfklow

### PR DESCRIPTION
**Pull request by chair28980**
Update readme to test PR assign worfklow

### CODE REVIEW

**Comment by chair28980** [comment]
:thinking:

**Comment by chair28980** [comment]
Interesting, looks to be failing on the flag add-assignee flag.

https://cli.github.com/manual/gh_pr_edit

**Comment by chair28980** [comment]
@chaitanyaprem @richard-ramos what are your thoughts on why this might be failing? I'm using the --add-assignee flag per: https://cli.github.com/manual/gh_pr_edit :sweat_smile:

**Comment by richard-ramos** [comment]
The command should probably be `gh pr edit` and not `gh pr update`

**Pull request closed without merging**
