### PR TITLE
refactor(peerExchange): use lru for storing peers

### PR DESCRIPTION
**Pull request by harsh-98**
Related to https://github.com/waku-org/go-waku/pull/531

### CODE REVIEW

**Comment by richard-ramos** [comment]
@harsh-98 It's the linter:
```
[2023-05-04T12:03:52.349Z] lint
[2023-05-04T12:04:51.533Z] waku/v2/protocol/peer_exchange/protocol.go:45:2: field `enrCacheMutex` is unused (unused)
[2023-05-04T12:04:51.533Z] 	enrCacheMutex sync.RWMutex
[2023-05-04T12:04:51.533Z] 	^
[2023-05-04T12:04:51.533Z] make: *** [Makefile:68: lint] Error 1

```

**Comment by harsh-98** [comment]
> @harsh-98 It's the linter:
> 
> ```
> [2023-05-04T12:03:52.349Z] lint
> [2023-05-04T12:04:51.533Z] waku/v2/protocol/peer_exchange/protocol.go:45:2: field `enrCacheMutex` is unused (unused)
> [2023-05-04T12:04:51.533Z] 	enrCacheMutex sync.RWMutex
> [2023-05-04T12:04:51.533Z] 	^
> [2023-05-04T12:04:51.533Z] make: *** [Makefile:68: lint] Error 1
> ```

Ran 
```
golangci-lint --exclude=SA1019 run ./... --deadline=5m -j 8
```
Got no error. But the test is still failing.

**Comment by richard-ramos** [comment]
This time the error happens in the testing stage. There's a panic due to timeout. Maybe some lock or waitgroup acting up. Logs can be seen here: https://gist.github.com/richard-ramos/ec27839b2a26c15b9a3f41dd8c103c4d

**Comment by richard-ramos** [comment]
This looks suspicious:
```
[2023-05-04T17:51:48.195Z] sync.runtime_Semacquire(0xc00227a401?)
[2023-05-04T17:51:48.195Z] 	runtime/sema.go:62 +0x25
[2023-05-04T17:51:48.195Z] sync.(*WaitGroup).Wait(0xc001816f00?)
[2023-05-04T17:51:48.195Z] 	sync/waitgroup.go:139 +0x52
[2023-05-04T17:51:48.195Z] github.com/waku-org/go-waku/waku/v2/protocol/relay.(*WakuRelay).Stop(0xc00181ef20)
[2023-05-04T17:51:48.195Z] 	github.com/waku-org/go-waku/waku/v2/protocol/relay/waku_relay.go:242 +0x89
[2023-05-04T17:51:48.195Z] github.com/waku-org/go-waku/waku/v2/node.(*WakuNode).Stop(0xc0028a2000)
[2023-05-04T17:51:48.195Z] 	github.com/waku-org/go-waku/waku/v2/node/wakunode2.go:452 +0x27b
[2023-05-04T17:51:48.195Z] github.com/waku-org/go-waku/waku/v2/node.TestWakuNode2(0xc001947040?)
```

**Review by richard-ramos — APPROVED** [review]
Very cool PR! thank you. Looks like there are some flakey tests in go-waku, but not related to this PR

**Pull request merged**
